### ISSUE TITLE
dpkg: dependency issues prevent mintstick setup on ubuntu 22.04

### ISSUE THREAD

**Issue by maravento** [linuxmint/mintstick#100]
Ubuntu 22.04 x64

Install:
```
wget http://packages.linuxmint.com/pool/main/m/mintstick/mintstick_1.4.7_all.deb
sudo dpkg -i mintstick_1.4.7_all.deb

dpkg: dependency issues prevent mintstick setup:
  mintstick depends on exfat-utils; Nevertheless:
   The `exfat-utils' package is not installed.

dpkg: error processing package mintstick (--install):
  dependency issues - left unconfigured
```
Ubuntu 22.04 has replaced "exfat-utils" with "exfatprogs"

```
sudo apt search exfat-utils
Sorting... Done
Search all text... Done
exfatprogs/jammy,now 1.1.3-1 amd64 [installed]
   tools to create, check and label exFAT filesystems
```

**Comment by xenopeek** [comment]
Thanks for reporting. This will be addressed for Linux Mint 21.

The package you downloaded is built for Linux Mint 20.x, for Ubuntu 20.04 LTS package base. To install mintstick on Ubuntu 22.04 LTS now you'd build it from source, after editing the debian/control file to update the dependency.

**Comment by madefromjames** [comment]
I fixed the dependencies issue to make `mintstick` work on Ubuntu 22.04 LTS (Jammy)

#### Initial Installation

Download and install the `mintstick` package:

```
wget http://packages.linuxmint.com/pool/main/m/mintstick/mintstick_1.4.7_all.deb
sudo dpkg -i mintstick_1.4.7_all.deb
```
If the application doesn't work, continue with the steps below to fix dependency issues:

#### 1. Create a Directory to Work In and Extract the `mintstick` Package

```
mkdir mintstick_extracted
dpkg-deb -R mintstick_1.4.7_all.deb mintstick_extracted
```

#### 2. Modify the Control File
Navigate to the DEBIAN directory and edit the control file:
```
cd mintstick_extracted/DEBIAN
nano control
```
Change the line:
```
Depends: gir1.2-xapp-1.0, exfat-utils
```
to:
```
Depends: gir1.2-xapp-1.0, exfatprogs
```
**Note:** You might find a line like this:
```
Depends: coreutils (>= 6.10-3), gir1.2-glib-2.0, gir1.2-gtk-3.0, gir1.2-polkit-1.0, ntfs-3g, parted, policykit-1, procps, python3, python3-gi, python3-parted, gir1.2-udisks-2.0, gir1.2-xapp-1.0, util-linux, exfat-utils
```
In this case, only change `exfat-utils` to `exfatprogs`.

Save and close the file.

#### 3. Rebuild the mintstick .deb Package
Navigate back to the parent directory and rebuild the .deb package:
```
cd ../..
dpkg-deb -b mintstick_extracted mintstick_1.4.7_all_modified.deb
```
#### 4. Install the Modified Package
Install the newly created package:
```
sudo dpkg -i mintstick_1.4.7_all_modified.deb
```
#### 5. Fix Any Broken Dependencies
In case there are any broken dependencies:
```
sudo apt --fix-broken install
```
