### ISSUE TITLE
Debian 12 - Installation impossible (issue with control.tar.zst)

### ISSUE THREAD

**Issue by Angedestenebres** [linuxmint/mintstick#103]
Hello,

During our first test with Debian 12 (unstable), we noticed an issue to install Mintstick, see screen.

![VirtualBox_EmmaDE5 Debian 12_17_06_2022_10_51_43](https://user-images.githubusercontent.com/21110485/174264231-8dfcd543-d51b-4218-95c9-32cf38e1020f.png)

Do you have a idea to fix that?

Thanks in advance for your answers.

**Comment by xenopeek** [comment]
Can you download the .deb file from https://packages.debian.org/sid/mintstick and run `LC_ALL=C sudo dpkg -i mintstick_1.4.9-1_all.deb` to get the output in English. And please copy the text, don't screenshot it.

**Comment by patrick-emmabuntus** [comment]
Thanks @xenopeek  for your link, and it works perfectly with gdebi or dpkg.

In the previous test we used this link http://packages.linuxmint.com/pool/main/m/mintstick/mintstick_1.4.9_all.deb and the data and control files are in the zstd format which is not supported by dpkg called by gdebi.

**Comment by Angedestenebres** [comment]
Thank you @xenopeek for your prompt answer :)

As a solution already exists, I close this ticket.
