### ISSUE TITLE
Does not run on Fedora

### ISSUE THREAD

**Issue by hazel-bunny** [linuxmint/mintstick#116]
Mintstick built for Fedora 38 in [my copr](https://copr.fedorainfracloud.org/coprs/hazel-bunny/ports) using [this spec](https://github.com/hazel-bunny/rpm-packaging/blob/main/apps/mintstick/mintstick.spec) does not start on Fedora 38. When started from terminal, it gives
```
$ mintstick
**
ERROR:../gi/gimodule.c:1840:_wrap_pyg_hook_up_vfunc_implementation: assertion failed: (G_TYPE_IS_CLASSED (implementor_gtype))
Bail out! ERROR:../gi/gimodule.c:1840:_wrap_pyg_hook_up_vfunc_implementation: assertion failed: (G_TYPE_IS_CLASSED (implementor_gtype))
/usr/bin/mintstick: line 9: 83360 Aborted                 (core dumped) $DIR/mintstick.py "$@"
```

**Comment by umikali222** [comment]
Mintstick isn't designed for fedora. Also, doesn't fedora come with it's own software for writing isos and formatting usbs?

**Comment by clefebvre** [comment]
I don't mind fixing it for it to work... but I don't have enough info here on what's actually the problem.. This error doesn't speak much to me.

**Comment by clefebvre** [comment]
Closing for now.
