### ISSUE TITLE
Wrong french translation

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mintstick#117]
Wrong french translation, should display **Souhaitez-vous** instead of **Souhaîtez-vous**:

![262751579-69ba3add-6b3c-4a23-906d-d1a52141dccb](https://github.com/linuxmint/mintstick/assets/3955499/53d97f18-ec4b-423e-b4f0-327233003d41)

**Steps to reproduce**:

Start mintstick. Choose an ISO file and write it on an USB key. Before starting writing, an advertisement message appears, with the wrong translation into it.

**Comment by carlosmintfan** [comment]
@InfoLibre you can fix this yourself by registering on launchpad.net (if you haven't already an Ubuntu One account) and joining the Linux Mint french translation team, for more info please visit https://linuxmint-translation-guide.readthedocs.io
Here is the translation: https://translations.launchpad.net/linuxmint/latest/+pots/mintstick/fr/+translate?batch=10&show=all&search=souh

**Comment by InfoLibre** [comment]
Done. Thank you for your help carlosmintfan!

**Comment by InfoLibre** [comment]
One year later, the translation isn't updated in Linux Mint Cinnamon 22. Did I make something wrong in the procedure?
https://translations.launchpad.net/linuxmint/latest/+pots/mintstick/fr/48/+translate
