### ISSUE TITLE
USB stick non recognized after being formated

### ISSUE THREAD

**Issue by escortgoj** [linuxmint/mintstick#118]
When formating to FAT32, the USB stick is not recognized/can't be mounted. As a result no iso can be written on it. I had to format it with gparted for it to be mounted eventually.
No issues when formating to exfat, ntfs or ext4.

Merci Clem pour cette distro qui m'accompagne depuis la version 5.0 👍

**Comment by clefebvre** [comment]
I think it's because of the É in CLÉ USB. I bumped into this issue today while fixing another bug.

This is fixed in the upcoming 1.6.0.
