### ISSUE TITLE
mintstick doesn't account for capital letters in sha256 checksum.

### ISSUE THREAD

**Issue by UselessWiz** [linuxmint/mintstick#120]
When verifying the checksum of an iso, if the checksum inputted contains capital letters (A-F), the verification process will fail. I noticed this when verifying a windows 10 iso, as the website provides checksums with capital letters. 

If we input the below checksum (from https://www.microsoft.com/en-us/software-download/windows10ISO),
![image](https://github.com/linuxmint/mintstick/assets/83886573/0354b06e-454f-4ee3-9e30-c4858ab27ce4)

We get this:
![image](https://github.com/linuxmint/mintstick/assets/83886573/9e2a5fa9-f348-4f11-8be4-dbba97e0c8d5)

However, manually checking over the calculated checksum and the provided checksum we can see they're the same.

I'm no expert with open-source development, but I'm more than happy to go digging through to see if I can fix it. I've already had a quick look through the code, but I'd just like to make sure there's no reason this hasn't been implemented already (like security or something).

**Comment by clefebvre** [comment]
No reason, this case (no pun intended) just didn't occur to us.
