### ISSUE TITLE
Can't burn ISO from external drive

### ISSUE THREAD

**Issue by zaivala** [linuxmint/mintstick#122]
This is a new issue with Mint 21.3, have not had the issue prior to upgrading a couple days ago.

When I use mintstick to burn an ISO which exists on an external SSD, it sets up properly, I click the "Write" button, it asks for my password ... and I get the usual write screen but nothing happens. I have tried this with different Linux ISOs. 

If I copy the ISO file from my external drive to my internal SSD, everything works. It does appear to be a lot slower than in the past, but I'm not certain the USB stick I was writing it to was USB3 so it could be that.

I have verified this with another user, he has the same issue (hadn't tried it until I prompted him to do so).

**Comment by zaivala** [comment]
![image](https://github.com/linuxmint/mintstick/assets/28702896/fbdbf5a2-887a-498a-b715-9ad75dcea02d)

**Comment by londoner366** [comment]
Can confirm this bug. However it seems related to issue #121 where the path to the external drive contains whitespace.
https://github.com/linuxmint/mintstick/commit/b88d2773d633f7506acaae1921414add7cb9a34a

**Comment by zaivala** [comment]
Thanks for your help and support.

Moss

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by clefebvre** [comment]
Fixed in upcoming version 1.6.0
