### ISSUE TITLE
[Request] No persistence file option

### ISSUE THREAD

**Issue by Lesbinary** [linuxmint/mintstick#31]
The main difference with Ubuntu USB Creator is the option for a persistence file. Is it possible here?

**Comment by unxed** [comment]
unetbootin does it well, maybe this functionality can be imported somehow?

**Comment by xenopeek** [comment]
Many thanks for contributing to mintstick. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
