### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by deivid-rodriguez** [linuxmint/mintstick#37]
When using mintstick, I get 100% CPU usage and it completely freezes my xorg process.

This seems related to https://github.com/tbehan/mintstick/commit/488e5572a5e2a1c5b49e1046a6ed7436692747d6#diff-8e748d5cf67ed7503036953ff4241f50R155, where @tbehan experiences (and fixes) this same problem. It seems that his enhacement was only partially introduced in https://github.com/linuxmint/mintstick/commit/3da82f0226b9c9eae565286bf8e95f64768c6c58 (without the fix). Later I think other stuff related to this have been fixed, but in my case it's still happening.

Commenting out https://github.com/linuxmint/mintstick/blob/master/lib/mintstick.py#L339 workarounds the problem (no percentage shown, but I can write my stick and my computer doesn't freeze).

Thanks!

**Comment by monsta** [comment]
Should be fixed by https://github.com/linuxmint/mintstick/commit/e6d98ebf83b43645634c4569a6450b7dd6a2037b.
