### ISSUE TITLE
Shell Command Injection

### ISSUE THREAD

**Issue by TheRegRunner** [linuxmint/mintstick#42]
https://bugs.launchpad.net/linuxmint/+bug/1460775

**Comment by GLolol** [comment]
Can you see if GLolol@9c1f4ca fixes this? I can't test now because I don't have flash drives to format.

**Comment by TheRegRunner** [comment]
Seems that the Fix works, thanks.

**Comment by TheRegRunner** [comment]
There are allover the same issues in each and every mint project !!

Could you please fix the other bugs i reported ...  
i ask you because noone else seems to care about the danger.
Thanks :-)

https://bugs.launchpad.net/~l-ubuntuone1104/+reportedbugs

**Comment by GLolol** [comment]
I can write patches, but I don't have a Linux box to test them atm.
