### ISSUE TITLE
Trouble with mintstick man-page

### ISSUE THREAD

**Issue by SaintDanbert** [linuxmint/mintstick#47]
The man page reads:
"
The full documentation for mintstick  is  maintained  at  http://github.com/linuxmint/mintstick
       Go to the project page to get access to the complete documentation.
"
However, I failed to find any explanation of the utility beyond an assumption to read the code.
While I am capable of doing that, I hardly call the available COPYING, TODO, and README
"complete documentation."

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintstick/commit/517cf9d249efc2db3c03520f39f23fd6bc2a832f
