### ISSUE TITLE
Use nemo as file chooser instead of default GTK file chooser

### ISSUE THREAD

**Issue by dqgls** [linuxmint/mintstick#50]
If I remember correctly mintstick in LM 17.x already uses nemo as file chooser, and other applications automatically use nemo as well. The default GTK file chooser does not have all the features (such as the recent files list) and looks a bit out of place from a UX viewpoint.

**Comment by xenopeek** [comment]
Thanks for contributing to mintstick. It would require Nemo to implement its own alternative to GtkFileChooserDialog (what mintstick currently uses). Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
