### ISSUE TITLE
Minor UI suggestions

### ISSUE THREAD

**Issue by dg1727** [linuxmint/mintstick#53]
(I've tested `mintstick` mostly as the global apps-menu icon "USB Stick Formatter" rather than as "USB Image Writer.")  

Suggestions:  
- Don't show the throbber at all until the `pkexec` dialog succeeds, because in some controls-themes (such as Mint-X), the blank throbber looks like an erroneously drawn control of some other kind.  
- If user cancels the `pkexec` dialog, then don't show an error message-box and don't animate the throbber.
- Add a version indication to the GUI, and a `--version` command-line option.  

`mintstick` APT package version 1.3.1

**Comment by xenopeek** [comment]
Many thanks for contributing to mintstick. 

Using mintstick version 1.3.5 and Mint-X theme on Linux Mint 18.3 Cinnamon it looks like the throbber is drawn correctly in both cases you describe. If in these cases the throbber is still drawn incorrectly for you, using those versions, something else must be the matter. In that case I suggest to go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintstick.

Your version command-line option suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by LinuxOnTheDesktop** [comment]
>  [. .] show an error message-box [. .]

This suboptimal and presumably easily fixed behaviour still occurs. Why not fix this papercut?
