### ISSUE TITLE
GitHub release and development status

### ISSUE THREAD

**Issue by baimafeima** [linuxmint/mintstick#54]
Is this project still maintained and if yes, could you release versioned tarballs here on GitHub?

**Comment by xenopeek** [comment]
Sorry for the late reply. We're bug squashing currently to improve on this. You can read more about it in last month's [monthly news](https://blog.linuxmint.com/?p=3509)). As you can see from the commit logs, mintstick is still developed.

I see we don't have tags or tarball releases, though you can find the version commits in the commit logs. Your suggestion to add those was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
