### ISSUE TITLE
format mode. mouse over at format selector pro/con unclear at FAT/exFAT (german translation)

### ISSUE THREAD

**Issue by Trombonista** [linuxmint/mintstick#86]
For FAT32 it says "- Kann nicht mit Dateien größer als 4GB umgehen" (i.e. con: can not work with files larger than 4GB).
For exFAT it says "- Kann mit Dateien größer als 4GB umgehen" (i.e. con: can work with files larger than 4GB).
That is misleading (AFAIK for exFAT the sentence is correct, but should be a pro instead of a con).
Btw: maybe also change 4GB to 4GiB?
Seen at Mint 20.1 cinnamon-edge (version number not available, see https://github.com/linuxmint/mintstick/issues/85).

**Comment by Trombonista** [comment]
with LANG="C" the "larger than 4GB" for exFAT is a pro as it should be, probably just a typo at the translation.

**Comment by xenopeek** [comment]
Making a note that the translation string for this is here: https://translations.launchpad.net/linuxmint/latest/+pots/mintstick/de/25/+translate

See also the translation guide for how you can help improve translations: https://linuxmint-translation-guide.readthedocs.io/en/latest/
