### ISSUE TITLE
Meson's polkit action breaks Mintstick's polkit action

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintstick#90]
Hi,

Polkit action of Meson package's breaks polkit action of Mintstick.

I guess, the issue is due to the following line including /usr/bin/python3 command.

From polkit action file of meson 

```
     <annotate key="org.freedesktop.policykit.exec.path">/usr/bin/python3</annotate>
     <annotate key="org.freedesktop.policykit.exec.argv1">/usr/bin/meson</annotate>
```

From polkit action file of mintstick

```
    <annotate key="org.freedesktop.policykit.exec.path">/usr/bin/python3</annotate>
    <annotate key="org.freedesktop.policykit.exec.argv1">/usr/lib/mintstick/raw_write.py</annotate>
    <annotate key="org.freedesktop.policykit.exec.argv1">/usr/lib/mintstick/raw_format.py</annotate>
    <annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
```

Any package including /usr/bin/python3 line in the polkit action file can also cause this issue. 

**Screenshot of issue**

![mintstick-polkit-action](https://user-images.githubusercontent.com/1300133/132587862-8d1ac8a3-e416-4a35-a6e7-1234370ca21a.png)

**Screenshot of expected behaviour**

![mintstick-polkit-action-2](https://user-images.githubusercontent.com/1300133/132588043-81cd81db-301b-4131-bd67-f6694d2aa4cb.png)

**Steps to reproduce**

Install meson package
Restart nemo with nemo -q command
Format an USB keyring

**Distribution**
Linux Mint 20.2 Uma Cinnamon

**Comment by clefebvre** [comment]
This is fixed in e02930c7334ad6ee238ea53226320fe08d001eec
