### ISSUE TITLE
[Feature request] Make info about each file system supported by the formatter more discoverable

### ISSUE THREAD

**Issue by AndreiMiculita** [linuxmint/mintstick#98]
Would be useful when formatting USB sticks, atm it requires googling each filesystem to find out (unless you're the kind of person who knows that by heart).

So for example, the dropdown would contain:
* FAT32 (Linux, macos, Windows)
* NTFS (Windows, Linux)
* EXT4 (Linux, Windows with special drivers)
etc

**Comment by xenopeek** [comment]
Perhaps it could be made more discoverable, but the dropdown box has a tooltip help if you hover your mouse cursor over the dropdown box (don't click it) which lists OS compatibility and pros and cons.

![image](https://user-images.githubusercontent.com/21159972/151550421-5de68e2c-fec8-4e66-af00-ae7d61fdb5f0.png)

**Comment by AndreiMiculita** [comment]
Nice to see it's already accounted for. Yes, it could be made more visible. For example, with an ℹ️ (information) button to the right of the dropdown box.

**Comment by axel358** [comment]
![_IMG_000000_000000](https://user-images.githubusercontent.com/72220889/165311672-523aa399-f7dc-4ea0-81ce-3cf90d587567.jpg)
How about this?

**Comment by AndreiMiculita** [comment]
> ![_IMG_000000_000000](https://user-images.githubusercontent.com/72220889/165311672-523aa399-f7dc-4ea0-81ce-3cf90d587567.jpg)
> How about this?

Looks good to me
